[compiler.solc]
exclude_paths = ["source/node_modules", "source/accounts", "source/packages", "source/examples/broadcast", "source/examples/node_modules", "source/examples/lib", "source/examples/script", "source/examples/test", "registry"]
include_paths = ["source/examples", "source/packages"]
remappings = [
    "forge-std/=source/examples/node_modules/forge-std/src/",
    "account-abstraction/=source/examples/node_modules/@ERC4337/account-abstraction/contracts/",
    "account-abstraction-v0.6/=source/examples/node_modules/@ERC4337/account-abstraction-v0.6/contracts/",
    "@openzeppelin/=source/examples/node_modules/@openzeppelin/",
    "erc7579/=source/examples/node_modules/erc7579/src/",
    "sentinellist/=source/examples/node_modules/sentinellist/src/",
    "solmate/=source/examples/node_modules/solmate/src/",
    "solady/=source/examples/node_modules/solady/src/",
    "solarray/=source/node_modules/solarray/src/",
    "@rhinestone/=source/node_modules/@rhinestone/",
    "@safe-global/=source/examples/node_modules/@safe-global/",
    "erc4337-validation/=source/examples/node_modules/erc4337-validation/src/",
    "@ERC4337/=source/examples/node_modules/@ERC4337/",
    "@prb/math/=source/examples/node_modules/@prb/math/",
    "checknsignatures/=source/examples/node_modules/checknsignatures/src/",
    "@rhinestone/safe7579/=source/accounts/safe7579/",
    "@rhinestone/registry/=registry/",
]

[compiler.solc.optimizer]
enabled = true

[detectors]
exclude_paths = ["source/node_modules", "source/accounts", "source/packages", "source/examples/broadcast", "source/examples/node_modules", "source/examples/lib", "source/examples/script", "registry"]
ignore_paths = ["source/examples/test"]

[testing]
cmd = "anvil"

[testing.anvil]
cmd_args = "--prune-history 100 --transaction-block-keeper 10 --steps-tracing --silent"

[testing.ganache]
cmd_args = "-k istanbul -q"

[testing.hardhat]
cmd_args = ""
